apiVersion: v1
kind: Service
metadata:
  name: release-sentinel-service
spec:
  type: NodePort
  selector:
    app: release-sentinel
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007